### ISSUE TITLE
remove Viewer

### ISSUE THREAD

**Issue by sibelius** [sibelius/ReactNavigationRelayModern#15]
depends on https://github.com/entria/graphql-dataloader-boilerplate/issues/46

**Comment by ssomnoremac** [comment]
@sibelius , what would this require? If you could provide a roadmap for this I could help. I'm starting again with Relay after a year and I've heard `viewer` is being depreciated.

**Comment by sibelius** [comment]
- [ ] send a PR to remove Viewer from our boilerplate https://github.com/entria/graphql-dataloader-boilerplate/issues/46 (move all fields from Viewer to QueryType, and refactor the rest of code)

- [ ] send a PR to remove Viewer from this boilerplate

let me know if you need any help

**Comment by ssomnoremac** [comment]
Hey @sibelius . thanks! I'm using my own server/schema and just got it working, I'm using [Absinthe](http://absinthe-graphql.org/) but I'll see about a PR here and there when I get a chance. This starter has been a great help getting up to speed with Modern. The only snag I've had has been passing `after: null` to a non-js backend.  But I think that's what the spec says so I'd rather not implement a work-around.

**Comment by ssomnoremac** [comment]
@sibelius , so is it `UserList_me`?

**Comment by ssomnoremac** [comment]
that doesn't make sense actually, shouldn't the type just be `UserList`? It's at the root so the `users` field is on directly on `props`, not nested.

**Comment by sibelius** [comment]
I think this could work

https://github.com/sibelius/ReactNavigationRelayModern/blob/master/src/UserList.js#L115

instead of 

`fragment UserList_query on Query`

**Comment by ssomnoremac** [comment]
@sibelius , thanks, but I'm having a hard time with this one because I haven't used fragments in a while:
so
```
 query: graphql`
      fragment UserList_query on Query{
        users( ...
```

then I have to do
```
query: graphql`
      query UserListPaginationQuery (
        $count: Int!,
        $cursor: String
      ) {
        ...UserList_query
      }
```
because there is no field `query` on Query; however, then there are no fields in the graphql response 
```Object {__fragments: Object, __id: "client:root"}```

**Comment by sibelius** [comment]
It is something like that, remember that Relay mask the data, only the component that asks for the data will see it this data

**Comment by ssomnoremac** [comment]
success! 🎉 

Thanks, yes, I forgot that, but had my `query={props.query}` 
needed to be `query={props}`

Submitting PR!

**Comment by sibelius** [comment]
fixed here https://github.com/sibelius/ReactNavigationRelayModern/pull/18
