### ISSUE TITLE
Remote server configuration

### ISSUE THREAD

**Issue by shahankit** [sibelius/ReactNavigationRelayModern#8]
In your demo app where and how should I do Remote server initialization. In previous Relay there was a call in `react-relay` for this: `Relay.injectNetworkLayer`. Can you please provide example with remote server configuration.

**Comment by sibelius** [comment]
it is much simple in `Relay Modern`

check the remote server configuration here: https://github.com/sibelius/ReactNavigationRelayModern/blob/master/src/createRelayEnvironment.js#L14

```jsx
// Define a function that fetches the results of an operation (query/mutation/etc)
// and returns its results as a Promise:
function fetchQuery(operation, variables, cacheConfig, uploadables) {
  return fetch('http://localhost:5000/graphql', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    }, // Add authentication and other headers here
    body: JSON.stringify({
      query: operation.text, // GraphQL text from input
      variables,
    }),
  }).then(response => {
    return response.json();
  });
}
```

**Comment by shahankit** [comment]
@sibelius Thanks for reply. Do I need separate fetch function for mutation or the same fetchQuery works for both query and mutation?

**Comment by sibelius** [comment]
the same `fetchQuery`

https://facebook.github.io/relay/docs/network-layer.html

**Comment by shahankit** [comment]
Okay thanks
